import http from 'node:http'
import https from 'node:https'
import { config } from './config.ts'
import { startBackupScheduler } from './backup.ts'
import { ensureCert, type CertInfo } from './tls.ts'
import { ensureSetupToken } from './setup.ts'
import { getMigrations } from 'better-auth/db/migration'
import { authOptions } from './auth-options.ts'
import { migrateAppSchema, userCount } from './db.ts'

/** How clients reach this server, for honest startup warnings. */
function connectionMode(): 'localhost' | 'lan-http' | 'lan-https' {
  let host = 'localhost'
  try {
    host = new URL(config.baseURL).hostname
  } catch {
    // fall through
  }
  const local = host === 'localhost' || host === '127.0.0.1' || host === '[::1]' || host === '::1'
  if (local) return 'localhost'
  return config.baseURL.startsWith('https://') ? 'lan-https' : 'lan-http'
}

async function main() {
  // Migrate before the auth instance exists: better-auth checks the schema as
  // soon as it is created and would report tables that are about to be made.
  const { runMigrations } = await getMigrations(authOptions)
  await runMigrations()
  migrateAppSchema()
  const { createApp } = await import('./app.ts')
  const app = await createApp()

  let cert: CertInfo | null = null
  if (config.tls) cert = ensureCert()
  const server = cert ? https.createServer({ cert: cert.cert, key: cert.key }, app) : http.createServer(app)

  startBackupScheduler()
  const setupToken = ensureSetupToken()
  const mode = connectionMode()

  server.listen(config.port, () => {
    const scheme = config.tls ? 'https' : 'http'
    console.log(`\n  Bugstow team server running on ${scheme}://localhost:${config.port}`)
    console.log(`  Base URL: ${config.baseURL}`)
    console.log(`  Data dir: ${config.dataDir}`)
    console.log(`  Offline mode: ${config.offline ? 'ON (GitHub import disabled)' : 'off'}`)
    if (cert) {
      console.log(`  HTTPS: on (${cert.generated ? 'self-signed certificate generated by BugsTow' : 'your certificate'})`)
      if (cert.hosts.length) console.log(`  Certificate covers: ${cert.hosts.join(', ')}`)
      console.log(`  Certificate SHA-256 fingerprint: ${cert.fingerprint256}`)
      console.log('  Teammates can download it from /api/tls/certificate to trust it (docs/RELEASE_OFFLINE.md §7).')
    } else {
      console.log('  HTTPS: off')
    }
    if (mode === 'lan-http') {
      console.log('\n  WARNING: teammates connect over plain HTTP. Passwords, session cookies and')
      console.log('  issue data travel unencrypted across your network, where anyone on it can read them.')
      console.log('  Set BUGSTOW_TLS=true and an https:// BUGSTOW_BASE_URL (docs/SELF_HOSTING.md §4).')
    } else if (mode === 'localhost') {
      console.log('  Address: localhost only (testing on this computer). For teammates, use the LAN setup with HTTPS.')
    }
    if (config.tls && !config.baseURL.startsWith('https://')) {
      console.log('\n  WARNING: BUGSTOW_TLS=true but BUGSTOW_BASE_URL starts with http://. Sign-in will fail; use https://.')
    }
    console.log(`  Auto-backups: ${config.backupEnabled ? `every ${config.backupIntervalHours}h, keep ${config.backupRetention}` : 'off'}`)
    console.log(
      config.backupExternalDir
        ? `  External backup copy: ${config.backupExternalDir} (keep ${config.backupExternalRetention})`
        : '  External backup copy: not configured (backups share a disk with the data; see docs/RELEASE_OFFLINE.md §8)'
    )
    const cloudTargets = [config.backupCloudDir && `folder ${config.backupCloudDir}`, config.backupWebdavUrl && 'WebDAV']
      .filter(Boolean)
      .join(' + ')
    if (cloudTargets) {
      console.log(
        config.backupEncryptionPassphrase
          ? `  Cloud backup: encrypted archives to ${cloudTargets}`
          : `  Cloud backup: ${cloudTargets} configured but BUGSTOW_BACKUP_ENCRYPTION_PASSPHRASE is missing, so nothing will be uploaded`
      )
      if (config.backupWebdavUrl.startsWith('http://')) {
        console.log('  Note: the WebDAV address uses http://. Archives are encrypted, but the WebDAV password is sent unencrypted.')
      }
    }
    if (setupToken && userCount() === 0) {
      console.log('\n  ┌─────────────────────────────────────────────────────────────')
      console.log('  │ First-time setup: no administrator exists yet.')
      console.log(`  │ Setup token: ${setupToken}`)
      console.log('  │ Open the server in a browser, choose "My team" and enter this')
      console.log('  │ token to create the administrator. It works once, then expires.')
      console.log('  └─────────────────────────────────────────────────────────────\n')
    } else {
      console.log('  Setup: complete. Teammates can sign in.\n')
    }
  })
}

main().catch(err => {
  console.error('Failed to start Bugstow server:', err)
  process.exit(1)
})
