import fs from 'node:fs'
import os from 'node:os'
import net from 'node:net'
import path from 'node:path'
import { X509Certificate } from 'node:crypto'
import selfsigned from 'selfsigned'
import { config } from './config.ts'

/**
 * HTTPS certificate handling for LAN use — entirely local, no cloud CA.
 *
 * If you supply your own certificate and key (BUGSTOW_TLS_CERT / _KEY, e.g.
 * from mkcert), they are used as-is and never touched. Otherwise BugsTow
 * generates a self-signed certificate valid for:
 *   - localhost and 127.0.0.1
 *   - the hostname/IP in BUGSTOW_BASE_URL (the address teammates use)
 *   - anything in BUGSTOW_TLS_HOSTS
 *   - this machine's non-internal IPv4 addresses (outside Docker)
 * Inside Docker the container cannot see the host's LAN IP, which is why the
 * BASE_URL host is always included.
 *
 * The generated certificate is recreated automatically when that host list
 * changes (e.g. BASE_URL moved to a new IP). Teammates trust it once; the
 * SHA-256 fingerprint is printed at startup so they can compare it with what
 * their browser shows.
 */

const GENERATED_MARKER = 'generated-hosts.json'

export interface CertInfo {
  cert: string
  key: string
  fingerprint256: string
  hosts: string[]
  generated: boolean
}

function wantedHosts(): string[] {
  const hosts = new Set<string>(['localhost', '127.0.0.1'])
  try {
    hosts.add(new URL(config.baseURL).hostname.replace(/^\[|\]$/g, ''))
  } catch {
    // invalid BASE_URL is reported elsewhere
  }
  for (const h of config.tlsHosts) hosts.add(h)
  for (const i of Object.values(os.networkInterfaces()).flat()) {
    if (i && i.family === 'IPv4' && !i.internal) hosts.add(i.address)
  }
  return [...hosts].sort()
}

function info(cert: string, key: string, hosts: string[], generated: boolean): CertInfo {
  return { cert, key, hosts, generated, fingerprint256: new X509Certificate(cert).fingerprint256 }
}

let current: CertInfo | null = null

/** The certificate the server is using, or null when HTTPS is off. */
export function getCurrentCert(): CertInfo | null {
  return current
}

export function ensureCert(): CertInfo {
  current = loadOrCreate()
  return current
}

function loadOrCreate(): CertInfo {
  const certPath = config.tlsCertPath
  const keyPath = config.tlsKeyPath
  const markerPath = path.join(path.dirname(certPath), GENERATED_MARKER)
  const hosts = wantedHosts()

  if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
    const cert = fs.readFileSync(certPath, 'utf8')
    const key = fs.readFileSync(keyPath, 'utf8')
    const x509 = new X509Certificate(cert)
    // Certificates generated by BugsTow 2.0.x have no marker file but use this name.
    const legacyGenerated = !fs.existsSync(markerPath) && /CN=bugstow\.local/.test(x509.subject)
    if (!fs.existsSync(markerPath) && !legacyGenerated) return info(cert, key, [], false) // your own certificate
    const previous = legacyGenerated
      ? (x509.subjectAltName || '').split(', ').map(s => s.replace(/^(DNS|IP Address):/, ''))
      : (JSON.parse(fs.readFileSync(markerPath, 'utf8')) as string[])
    const expiresSoon = new Date(new X509Certificate(cert).validTo).getTime() - Date.now() < 30 * 86400_000
    if (!expiresSoon && hosts.every(h => previous.includes(h))) return info(cert, key, previous, true)
    console.log(
      expiresSoon
        ? '  TLS: the self-signed certificate is about to expire, generating a new one (teammates must trust it again).'
        : '  TLS: the server address changed, generating a new self-signed certificate (teammates must trust it again).'
    )
  }

  const altNames = hosts.map(h =>
    net.isIP(h) ? { type: 7 as const, ip: h } : { type: 2 as const, value: h }
  )
  const pems = selfsigned.generate([{ name: 'commonName', value: 'BugsTow team server' }], {
    // Apple platforms reject TLS server certificates valid for more than 825
    // days or without the serverAuth usage.
    days: 825,
    keySize: 2048,
    algorithm: 'sha256',
    extensions: [
      { name: 'keyUsage', digitalSignature: true, keyEncipherment: true },
      { name: 'extKeyUsage', serverAuth: true },
      { name: 'subjectAltName', altNames },
    ],
  })

  fs.writeFileSync(keyPath, pems.private, { mode: 0o600 })
  fs.writeFileSync(certPath, pems.cert)
  fs.writeFileSync(markerPath, JSON.stringify(hosts))
  return info(pems.cert, pems.private, hosts, true)
}
