import { test } from 'node:test'
import assert from 'node:assert/strict'
import os from 'node:os'
import path from 'node:path'
import fs from 'node:fs'
import { X509Certificate, createPrivateKey } from 'node:crypto'

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bugstow-tls-'))
process.env.BUGSTOW_DATA_DIR = tmp
process.env.BUGSTOW_AUTH_SECRET = 'test-secret-abcdefghijklmnop'
// Inside Docker the host's LAN IP is only known from BASE_URL.
process.env.BUGSTOW_BASE_URL = 'https://192.168.50.7:8080'
process.env.BUGSTOW_TLS_HOSTS = 'bugstow.lan'

const { config } = await import('./config.ts')
const { ensureCert } = await import('./tls.ts')

test('the generated certificate covers the BASE_URL host and extra hosts', () => {
  const info = ensureCert()
  const x509 = new X509Certificate(info.cert)
  assert.match(x509.subjectAltName || '', /IP Address:192\.168\.50\.7/)
  assert.match(x509.subjectAltName || '', /DNS:bugstow\.lan/)
  assert.match(x509.subjectAltName || '', /DNS:localhost/)
  assert.ok(x509.checkPrivateKey(createPrivateKey(info.key)), 'key matches certificate')
})

test('the certificate is acceptable to Apple devices (<= 825 days, serverAuth)', () => {
  const x509 = new X509Certificate(ensureCert().cert)
  const days = (new Date(x509.validTo).getTime() - new Date(x509.validFrom).getTime()) / 86400_000
  assert.ok(days <= 825, `valid for ${days} days`)
  assert.ok(x509.keyUsage?.includes('1.3.6.1.5.5.7.3.1'), 'extended key usage serverAuth')
})

test('restarting keeps the same certificate', () => {
  assert.equal(ensureCert().fingerprint256, ensureCert().fingerprint256)
})

test('a new server address produces a new certificate', () => {
  const before = ensureCert().fingerprint256
  ;(config as { baseURL: string }).baseURL = 'https://10.0.0.9:8080'
  const after = ensureCert()
  assert.notEqual(after.fingerprint256, before)
  assert.match(new X509Certificate(after.cert).subjectAltName || '', /IP Address:10\.0\.0\.9/)
})

test('a certificate you supply yourself is never replaced', () => {
  fs.rmSync(path.join(config.certsDir, 'generated-hosts.json'))
  const own = fs.readFileSync(config.tlsCertPath, 'utf8')
  ;(config as { baseURL: string }).baseURL = 'https://172.16.0.4:8080'
  const info = ensureCert()
  assert.equal(info.generated, false)
  assert.equal(info.cert, own)
})


test('a certificate generated by BugsTow 2.0.x is upgraded when it misses the server address', async () => {
  const selfsigned = (await import('selfsigned')).default
  const legacy = selfsigned.generate([{ name: 'commonName', value: 'bugstow.local' }], {
    days: 3650,
    keySize: 2048,
    algorithm: 'sha256',
    extensions: [{ name: 'subjectAltName', altNames: [{ type: 2, value: 'localhost' }] }],
  })
  fs.writeFileSync(config.tlsCertPath, legacy.cert)
  fs.writeFileSync(config.tlsKeyPath, legacy.private)
  ;(config as { baseURL: string }).baseURL = 'https://192.168.1.20:8080'
  const info = ensureCert()
  assert.equal(info.generated, true)
  assert.notEqual(info.cert, legacy.cert)
  assert.match(new X509Certificate(info.cert).subjectAltName || '', /IP Address:192\.168\.1\.20/)
})
